### ISSUE TITLE
Microsoft Edge WebDriver 115+ fails to launch browser with "cannot find msedge binary" on Linux

### ISSUE THREAD

**Issue by nkns165** [MicrosoftEdge/EdgeWebDriver#102]
## Summary

Microsoft Edge WebDriver 115 itself successfully starts, but when I start a session with it, it cannot launch Microsoft Edge browser and stops at the error like

```
{"error": "unknown error", "message": "unknown error: cannot find msedge binary"}
```

## Environment

- Browser (Microsoft Edge) Version: 115.0.1901.188
- Driver Version: 115.0.1901.188
- OS: Ubuntu 20.04

I confirmed that the problem doesn't happen on Windows and macOS.
Also, it doesn't happen on Ubuntu with Driver Version 114.0.1823.82.

## How to reproduce

I was able to reproduce the problem on a Docker container with image `ubuntu:20.04`.

```
apt update
apt install software-properties-common apt-transport-https wget curl git unzip -y
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | apt-key add -
sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-stable.list'
apt update
apt install microsoft-edge-stable -y
microsoft-edge --version
wget https://msedgedriver.azureedge.net/115.0.1901.188/edgedriver_linux64.zip
unzip edgedriver_linux64.zip
./msedgedriver &
curl http://localhost:9515/status
curl -X POST http://localhost:9515/session -d '{"capabilities": {"browserName": "MicrosoftEdge"}}'
```

Here, I've got the error message described above.
I've confirmed the browser is surely installed by the following command (I've got `Microsoft Edge 115.0.1901.188`).

```
microsoft-edge --version
```

Next, I've checked the behavior of Driver Version 114.0.1823.82.

```
mv msedgedriver msedgedriver-115
wget https://msedgedriver.azureedge.net/114.0.1823.82/edgedriver_linux64.zip
unzip edgedriver_linux64.zip
./msedgedriver &
curl -X POST http://localhost:9515/session -d '{"capabilities": {"browserName": "MicrosoftEdge"}}'
```

I've got another error message, but this is because I've not set up the other required components like Xvfb. At least, the browser tried to launch once. So the problem is limited within version 115.

```
{"error": "unknown error", "message": "unknown error: MicroSoft Edge failed to start: exited abnormally. (omitted)"}
```

## Other

I guess this issue is similar to https://bugs.chromium.org/p/chromium/issues/detail?id=1466427 where ChromeDriver couldn't find Chrome binary (the issue was limited to macOS, though).

When we tried Microsoft Edge WebDriver 115 where both MicroSoft Edge and Chrome exist, we've got a different error message.

```
{"error": "unknown error", "message": "unknown error: unknown error: unrecognized Microsoft Edge version: Chrome/115.0.5790.110"}
```

AB#45872325

**Comment by amardeep2006** [comment]
I faced the same issue with Edge Version 115. 
The behavior is explained here .  https://github.com/SeleniumHQ/docker-selenium/issues/1910

**Comment by Wolfe1** [comment]
Same issue with Edge 115, downgrade to 114 mitigates for now.

**Comment by bwalderman** [comment]
Thank you for reporting this. I've added it to our internal backlog for investigation.

**Comment by joeyparrish** [comment]
I noticed that msedgedriver 115.0.1901.203 on Linux actually launches `/opt/google/chrome/chrome` instead of `/opt/microsoft/msedge/msedge`.  The same is true of 116.0.1938.51 and 117.0.2033.0, but not 114.0.1823.82.

I hope that helps!

**Comment by joeyparrish** [comment]
For now, all our automation will have to use msedgedriver 114 for any Edge version 115+.  (See https://github.com/shaka-project/webdriver-installer/pull/32)  I suspect this will not be a viable workaround forever, since newer Edge releases might not be able to communicate with older drivers if something in the protocol changes.  Please let us know if we can expect a fix before that happens.  Thanks!

**Comment by nkns165** [comment]
@joeyparrish Thank you for your additional information. Also, thanks to https://github.com/actions/runner-images/issues/8046 I learned that the previous version 115.0.1901.183 works well for Edge 115. It can be another workaround.

But as for Edge 116+, I have the same concern with https://github.com/MicrosoftEdge/EdgeWebDriver/issues/102#issuecomment-1684245931. I hope it will be fixed soon.

**Comment by nkns165** [comment]
@bwalderman Is there any update? I've confirmed that the latest version 116.0.1938.69 still has the same problem.
Now we cannot upgrade Edge in our test environment...

**Comment by joeyparrish** [comment]
Edge 116 is out on GitHub VMs, and the workaround of using driver version 114 no longer works:

```
session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 114
Current browser version is 116.0.1938.69 with binary path /usr/bin/microsoft-edge
```

Feeling good about [my prediction 3 weeks ago](https://github.com/MicrosoftEdge/EdgeWebDriver/issues/102#issuecomment-1684245931) that 116 could break things...

Any comment from Microsoft on [the observation that msedgedriver wants to run `/opt/google/chrome/chrome`](https://github.com/MicrosoftEdge/EdgeWebDriver/issues/102#issuecomment-1684236354)?  It seems like if there's a mistaken path in msedgedriver, that should be relatively easy to fix, right?

Another workaround that still works:  In your capabilities request, specify `"ms:edgeOptions": { "binary": "/usr/bin/microsoft-edge" }`

**Comment by tkoukkari** [comment]
> Edge 116 is out on GitHub VMs, and the workaround of using driver version 114 no longer works:
> 
> ```
> session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 114
> Current browser version is 116.0.1938.69 with binary path /usr/bin/microsoft-edge
> ```
> 
> Feeling good about [my prediction 3 weeks ago](https://github.com/MicrosoftEdge/EdgeWebDriver/issues/102#issuecomment-1684245931) that 116 could break things...
> 
> Any comment from Microsoft on [the observation that msedgedriver wants to run `/opt/google/chrome/chrome`](https://github.com/MicrosoftEdge/EdgeWebDriver/issues/102#issuecomment-1684236354)? It seems like if there's a mistaken path in msedgedriver, that should be relatively easy to fix, right?
> 
> Another workaround that still works: In your capabilities request, specify `"ms:edgeOptions": { "binary": "/usr/bin/microsoft-edge" }`

Just to highlight that this combination still works:
```
Browser version: 116.0.1938.69
Edgedriver version: 115.0.1901.183 (db29db5e66a28f9f889ff1962ead6e0c377200e0)
```

...but probably only until Edge 117. It seems that whatever was changed in driver version **115.0.1901.188** caused this. Any chance of reviewing those changes and maybe reverting the one that is causing this?

**Comment by Prajakta365** [comment]
facing same issue for edge driver version 117.0.2045.35
`ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: unrecognized Microsoft Edge version: HeadlessChrome/117.0.5938.88 ERROR webdriver: unknown error: unknown error: unrecognized Microsoft Edge version: HeadlessChrome/117.0.5938.88`

**Comment by bwalderman** [comment]
Hi folks. Sorry for the delays in addressing this. We've fixed the issue in msedgedriver and the fix will be available on the Edge Canary channel within a day or two. We're also working to backport this change to the Beta and Stable channels, which will take an additional few days.

Until the fix lands, you can work around this issue on Linux by setting the browser binary location in your EdgeOptions to `/usr/bin/microsoft-edge` explicitly.

**Comment by merinsTDL** [comment]
Good day! 
Still getting the same error:
Platform: Linux AMD64 (Ubuntu Jammy)
MS Edge: 119.0.2109.1-1 (microsoft-edge-dev)
Driver: 119.0.2109.1 (https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/119.0.2109.1/edgedriver_linux64.zip)
Error when starting the driver: 500. Message: unknown error: cannot find msedge binary

**Comment by Goraved** [comment]
Any updates on this? This issue really blocks us from using Edge > 114 version

**Comment by jayhome** [comment]
> Hi folks. Sorry for the delays in addressing this. We've fixed the issue in msedgedriver and the fix will be available on the Edge Canary channel within a day or two. We're also working to backport this change to the Beta and Stable channels, which will take an additional few days.
> 
> Until the fix lands, you can work around this issue on Linux by setting the browser binary location in your EdgeOptions to `/usr/bin/microsoft-edge` explicitly.

hi Brandon, 
Will the fix automatically find it's way to https://hub.docker.com/r/selenium/node-edge/ (dev -> beta -> latest)?

**Comment by renataknowhow** [comment]
Any updates on this guys? It's being broke for more than a month already. @jayhome I tried to pull selenium node edge, integrate in a CI/CD environment, it didn't fix the error 'E       selenium.common.exceptions.WebDriverException: Message: unknown error: unrecognized Microsoft Edge version: Chrome/117.0.5938.0'.

**Comment by jayhome** [comment]
> "unknown error: cannot find msedge binary"
I was only able to use and run dev version 119 (not 117 latest) without getting the error as mentioned in the issue summary: "unknown error: cannot find msedge binary". But ran into stability issues rendering the dev build useless for my testing purpose. 
You seem to have a different error/problem, possibly unrelated to the forementioned root cause: incorrect browser binary location.
