### ISSUE TITLE
Download Page Changed, Missing Link to 102.0.1245.39

### ISSUE THREAD

**Issue by stevensmith01** [MicrosoftEdge/EdgeWebDriver#31]
URL: https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

There is a missing link to version 102.0.1245.39 within the Release 102 section at the bottom of the page. I also noticed that the 3 of the 4 sections at the top are now missing. We use these links to automate the download of our web drivers. If they are missing and our browsers update to this version, we cannot operate.

**Comment by bwalderman** [comment]
Thank you for reporting this. The page has been fixed and all versions should be available again.

**Comment by stevensmith01** [comment]
@bwalderman The download page is still not updated to show version 103.0.1264.44. Is there another way to determine when a new version is available to download? I use this page to download the web driver to a local repository so my users are downloading files from our local network. If the download links are not updated we will have users with issues when their browsers automatically update.
