### ISSUE TITLE
Handle "disable popup blocker" does not work in Edge with IE-Mode

### ISSUE THREAD

**Issue by harsha509** [MicrosoftEdge/EdgeWebDriver#36]
HI There,

Looking into this https://github.com/MicrosoftDocs/edge-developer/issues/1674, would like to know if this resolved or any work around is available. My team is currently testing edge in IE mode but unable to handle popup blocking. setting capability '--disable-popup-blocking'

Tried with work around mentioned it in https://github.com/MicrosoftDocs/edge-developer/issues/1674. but it didn't work for us!

`gpedit (edit group policy) > administrative templates > windows components > internet explorer > internet control panel > security page > internet zone (or your actual zone) > use popup blocker (it must be enabled with the inner dropdown set to disabled).`

**Comment by bwalderman** [comment]
Hi @harsha509. IEDriver doesn't support passing additional command line args to Edge.

If you run msedge.exe manually from the command line with `--disable-popup-blocking`, does it have the desired effect in IE Mode? If so, then we can submit a PR to Selenium to include it in the default list of command line args that are used to launch Edge.

**Comment by ravibabu101143** [comment]
> Hi @harsha509. IEDriver doesn't support passing additional command line args to Edge.
> 
> If you run msedge.exe manually from the command line with `--disable-popup-blocking`, does it have the desired effect in IE Mode? If so, then we can submit a PR to Selenium to include it in the default list of command line args that are used to launch Edge.

I have tried this option in command line, popups are not blocked. can I assume microsoft is not  going to take care of this to resolve at browser  but we will be submitting new enhancement request with selenium. Is my understanding correct? Currently we started POC and we are blocked due to this issue as disabling popup as group policy is not possible in our organization

**Comment by ravibabu101143** [comment]
> > I have tried this option in command line, popups are not blocked.
> 
> Thank you for confirming. I've created a PR [SeleniumHQ/selenium#10869](https://github.com/SeleniumHQ/selenium/pull/10869) to include this flag when launching IE Mode.

Thank you for the fix. How can i get the latest selenium jar with this fix? Can you guide me on this?

**Comment by ravibabu101143** [comment]
Can any one suggest, how to get this fix?

**Comment by bwalderman** [comment]
The fix should be available in the next IEDriver release. Our team contributes fixes to [Selenium](https://github.com/SeleniumHQ/selenium) but we don't manage IEDriver releases.  Please contact the Selenium maintainers for questions about the release schedule.

**Comment by harsha509** [comment]
We've released it.

https://github.com/SeleniumHQ/selenium/blob/trunk/cpp/iedriverserver/CHANGELOG

you can get it from selenium.dev

**Comment by ravibabu101143** [comment]
> We've released it.
> 
> https://github.com/SeleniumHQ/selenium/blob/trunk/cpp/iedriverserver/CHANGELOG
> 
> you can get it from selenium.dev

I have not found v4.3.0.0 in selenium.dev download link. I am sorry incase if i am looking at wrong place. I am still seeing  4.2.0.0 version for internet explorer driver. Can you help to get download path to the version that has this fix?

**Comment by harsha509** [comment]
Ah,

I have updated the download links. You can get it from here https://www.selenium.dev/downloads/

**Comment by ravibabu101143** [comment]
> Ah,
> 
> I have updated the download links. You can get it from here https://www.selenium.dev/downloads/

Thank you. Now i see updated version. I tested the fix and it is working. Thank you every one for the quick fix.
